STORAGE:
  BATTERY:
    capital_cost_storage: 100000
    mode_of_operation_charge: 1
    mode_of_operation_discharge: 57
    operational_life_storage: 25
    residual_storage_capacity: 0
    status: future
    storage_max_capacity: 99999
    technology_from_storage: BATTERY_STORAGE
    technology_to_storage: BATTERY_STORAGE
  HYDRODAM01:
    capital_cost_storage: 999999
    mode_of_operation_charge: 1
    mode_of_operation_discharge: 57
    operational_life_storage: 100
    residual_storage_capacity: 69.39855405618714
    status: existing
    storage_max_capacity: 69.39855405618714
    technology_from_storage: PWRHYDB01
    technology_to_storage: INFLOW01
STORAGE_TECHNOLOGY:
  BATTERY_STORAGE:
    capital_cost: 100000
    operational_life: 25
    variable_cost: 100000
TECHNOLOGIES:
  CCS:
    CCS01:
      capital_cost: 9999
      operational_life: 20
      total_annual_max_capacity: 0.5
      total_annual_max_capacity_investment:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 1
      total_annual_min_capacity: 0.2
  HDG:
    HDG02:
      capital_cost: 20
      efficiency: 0.7
      input_fuel: NGS
      operational_life: 20
      total_annual_max_capacity: 30
  INFLOW:
    INFLOW01:
      capacity: 13.80168961708861
      capacity_storage: 68.94037623826668
      capital_cost: 0
      closure_year: 2050
      name:
      - BC_ALH_RES
      - BC_ALU_RES
      - BC_BR1_RES
      - BC_GMS_RES
      - BC_JHT_RES
      - BC_LDR_RES
      - BC_MCA_RES
      - BC_PCN_RES
      - BC_REV_RES
      - BC_RUS_RES
      - BC_SCA_RES
      - BC_SEV_RES
      - BC_SFL_RES
      - BC_SON_RES
      - BC_STC_RES
      - BC_WGS_RES
      operational_life: 99
  PWRBIO:
    PWRBIOB01:
      availability_factor: 0.8497798971482001
      capacity: '[0.00103, 0.00103, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0]'
      capital_cost: 2076.52
      efficiency: 0.40081541585023794
      operational_life: 8
      total_annual_max_capacity_investment: 0
      variable_cost: 8.1
    PWRBIOB02:
      availability_factor: 0.44328429640844474
      capacity: '[0.1109, 0.1109, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0]'
      capital_cost: 6000.15
      efficiency: 0.2527512322320797
      operational_life: 30
      total_annual_max_capacity_investment: 0
      variable_cost: 6.58
  PWRGEO:
    PWRGEOB01:
      total_annual_max_capacity_investment: 0
  PWRHYD:
    PWRHYDB01:
      capacity: 12.41801
      capital_cost: 4007.9
      closure_year: 2050
      input ratio: 1
      operational_life: 100
      status: existing
      total_annual_max_capacity: 12.41801
      total_annual_max_capacity_investment: 0
      type: reservoir
    PWRHYDB02:
      capacity: 5.314639999999999
      capital_cost: 4007.9
      closure_year: 2050
      operational_life: 100
      status: existing
      total_annual_max_capacity: 5.314639999999999
      total_annual_max_capacity_investment: 0
      type: ror
  PWRNGS:
    PWRNGSB01:
      availability_factor: 0.9064294901240239
      capacity: '[0.275, 0.275, 0.275, 0.275, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0]'
      capital_cost: 1408.21
      efficiency: 0.5365002570963955
      operational_life: 21
      total_annual_max_capacity_investment: 0
      variable_cost: 2.55
    PWRNGSB02:
      availability_factor: 0.7991
      capacity: '[0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24, 0.24,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0]'
      capital_cost: 3772.47
      efficiency: 0.4765560942923289
      operational_life: 37
      total_annual_max_capacity_investment: 0
      variable_cost: 7.94
  PWRSOL:
    PWRSOLB01:
      capacity: 0.0011
      capital_cost: 1759.6
      closure_year: 2040
      name: BC_SNM00_GEN
      operational_life: 30
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRSOLB02:
      capital_cost: 1482.68328030212
      name: ShTSaQU Solar Project
      operational_life: 20.0
      potential: 0.104
      start_year: 2030
      status: future
      variable_cost: 23.76559999999999
    PWRSOLB03:
      capital_cost: 1482.68
      name: GreaterVancouver_1
      operational_life: 25.0
      potential: 0.8717157748186453
      start_year: 2031
      status: future
      variable_cost: 0.0
    PWRSOLB04:
      capital_cost: 1482.68
      name: KootenayBoundary_1
      operational_life: 25.0
      potential: 2.3531367122608264
      start_year: 2031
      status: future
      total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
      total_annual_max_capacity_investment:
      - 0
      - 0
      - 0
      - 0
      variable_cost: 0.0
    PWRSOLB05:
      capital_cost: 1482.68
      name: Capital_1
      operational_life: 25.0
      potential: 0.0033489523065215417
      start_year: 2031
      status: future
      total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
      total_annual_max_capacity_investment: '[0,0,0,0]'
      variable_cost: 0.0
    PWRSOLB06:
      capital_cost: 1482.68
      name: CentralOkanagan_1
      operational_life: 25.0
      potential: 1.0769436162124921
      start_year: 2031
      status: future
      total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
      total_annual_max_capacity_investment: '[0,0,0,0,0,0,0,0,0,0,0]'
      variable_cost: 0.0
    PWRSOLB07:
      capital_cost: 1482.68
      name: NorthOkanagan_1
      operational_life: 25.0
      potential: 0.6948549444015153
      start_year: 2031
      status: future
      total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
      total_annual_max_capacity_investment: '[0,0,0,0,0,0,0,0,0,0,0]'
      variable_cost: 0.0
  PWRURN:
    PWRURNB01:
      capital_cost: 6041
      efficiency: 0.3333
      input_fuel: PWRURN
      operational_life: 36
      total_annual_max_capacity_investment: 0
  PWRWND:
    PWRWNDB01:
      capacity: 0.102
      capital_cost: 2278.07
      closure_year: 2034
      name: BC_BMW00_GEN
      operational_life: 25
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB02:
      capacity: 0.0992
      capital_cost: 2278.07
      closure_year: 2033
      name: BC_CSS00_GEN
      operational_life: 20
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB03:
      capacity: 0.144
      capital_cost: 2278.07
      closure_year: 2036
      name: BC_DKW00_GEN
      operational_life: 25
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB04:
      capacity: 0.1846
      capital_cost: 2278.07
      closure_year: 2040
      name: BC_MKL00_GEN
      operational_life: 25
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB05:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 2059
      name: BC_MLW00_GEN
      operational_life: 40
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB06:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 2050
      name: BC_PSW00_GEN
      operational_life: 40
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB07:
      capacity: 0.1422
      capital_cost: 2278.07
      closure_year: 2037
      name: BC_QTY00_GEN
      operational_life: 25
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB08:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 2050
      name: BC_SHC00_GEN
      operational_life: 40
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB09:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 2061
      name: BC_SUK00_GEN
      operational_life: 40
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB10:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 2061
      name: BC_ZBK00_GEN
      operational_life: 40
      status: existing
      total_annual_max_capacity_investment: 0
      variable_cost: 0.0
    PWRWNDB11:
      capital_cost: 1735.2745158554371
      name: Stewart Creek Wind Project
      operational_life: 20.0
      potential: 0.1999
      start_year: 2031
      status: future
      variable_cost: 41.2222
    PWRWNDB12:
      capital_cost: 1735.2745158554371
      name: Nithi Mountain Wind Project
      operational_life: 20.0
      potential: 0.1999
      start_year: 2031
      status: future
      variable_cost: 41.2222
    PWRWNDB13:
      capital_cost: 1735.2745158554371
      name: Highland Valley Wind Project
      operational_life: 20.0
      potential: 0.1972
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB14:
      capital_cost: 1735.2745158554371
      name: Mount Mabel Wind Project
      operational_life: 20.0
      potential: 0.1428
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB15:
      capital_cost: 1735.2745158554371
      name: K2 Wind Project
      operational_life: 20.0
      potential: 0.1596
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB16:
      capital_cost: 1735.2745158554371
      name: Nilhts'i Ecoener Project (Formerly Hixon Wind Power Project)
      operational_life: 20.0
      potential: 0.1404
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB17:
      capital_cost: 1735.2745158554371
      name: Brewster Wind Project
      operational_life: 20.0
      potential: 0.1972
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB18:
      capital_cost: 1735.2745158554371
      name: Boulder and Elkhart Wind Project
      operational_life: 20.0
      potential: 0.09440000000000001
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB19:
      capital_cost: 1735.2745158554371
      name: Taylor Wind Project
      operational_life: 20.0
      potential: 0.2
      start_year: 2032
      status: future
      variable_cost: 41.2222
    PWRWNDB20:
      capital_cost: 1735.0
      name: CentralOkanagan_1
      operational_life: 20.0
      potential: 1.4656673577941173
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB21:
      capital_cost: 1735.0
      name: Capital_1
      operational_life: 20.0
      potential: 0.0069288668410790516
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB22:
      capital_cost: 1735.0
      name: GreaterVancouver_1
      operational_life: 20.0
      potential: 0.11544805215270242
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB23:
      capital_cost: 1735.0
      name: MountWaddington_1
      operational_life: 20.0
      potential: 1.0989201904394237
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB24:
      capital_cost: 1735.0
      name: Nanaimo_1
      operational_life: 20.0
      potential: 0.48593355113910613
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB25:
      capital_cost: 1735.0
      name: Alberni-Clayoquot_1
      operational_life: 20.0
      potential: 0.11532233793021796
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB26:
      capital_cost: 1735.0
      name: Comox-Strathcona_1
      operational_life: 20.0
      potential: 0.0
      start_year: 2033
      status: future
      variable_cost: 0.0
    PWRWNDB27:
      capital_cost: 1735.0
      name: PeaceRiver_1
      operational_life: 20.0
      potential: 6.711779643703353
      start_year: 2033
      status: future
      variable_cost: 0.0
