STORAGE:
  BATTERY:
    capital_cost_storage: 100000
    mode_of_operation_charge: 1
    mode_of_operation_discharge: 57
    operational_life_storage: 25
    residual_storage_capacity: 0.05
    status: future
    storage_max_capacity: 99999
    technology_from_storage: BATTERY_STORAGE
    technology_to_storage: BATTERY_STORAGE
  HYDRODAM01:
    capital_cost_storage: 999999
    mode_of_operation_charge: 1
    mode_of_operation_discharge: 57
    operational_life_storage: 100
    residual_storage_capacity: 69.39855405618714
    status: existing
    storage_max_capacity: 69.39855405618714
    technology_from_storage: PWRHYDB01
    technology_to_storage: INFLOW01
STORAGE_TECHNOLOGY:
  BATTERY_STORAGE:
    capital_cost: 1.0
    operational_life: 25
    variable_cost: 0.0
TECHNOLOGIES:
  INFLOW:
    INFLOW01:
      capacity: 13.80168961708861
      capacity_storage: 68.94037623826668
      capital_cost: 0
      closure_year: 2050
      name:
      - BC_ALH_RES
      - BC_ALU_RES
      - BC_BR1_RES
      - BC_GMS_RES
      - BC_JHT_RES
      - BC_LDR_RES
      - BC_MCA_RES
      - BC_PCN_RES
      - BC_REV_RES
      - BC_RUS_RES
      - BC_SCA_RES
      - BC_SEV_RES
      - BC_SFL_RES
      - BC_SON_RES
      - BC_STC_RES
      - BC_WGS_RES
      operational_life: 99
  PWRBIO:
    PWRBIOB01:
      availability_factor: 0.8497798971482001
      capacity: '[0.00103, 0.00103, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0]'
      capital_cost: 2076.52
      efficiency: 0.40081541585023794
      operational_life: 8
      variable_cost: 8.1
    PWRBIOB02:
      availability_factor: 0.44328429640844474
      capacity: '[0.1109, 0.1109, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0]'
      capital_cost: 6000.15
      efficiency: 0.2527512322320797
      operational_life: -2013
      variable_cost: 6.58
  PWRHYD:
    PWRHYDB01:
      capacity: 12.41801
      capital_cost: 4007.9
      closure_year: 2050
      input ratio: 1
      operational_life: -1951
      status: existing
      type: reservoir
    PWRHYDB02:
      capacity: 5.314639999999999
      capital_cost: 4007.9
      closure_year: 2050
      operational_life: -2009
      status: existing
      type: ror
  PWRNGS: {}
  PWRSOL:
    PWRSOLB01:
      capacity: 0.0011
      capital_cost: 1759.6
      closure_year: 0
      name: BC_SNM00_GEN
      operational_life: -2010
      status: existing
      variable_cost: 0.0
    PWRSOLB02:
      capital_cost: 1482.6832803021205
      name: East Kootenay_1
      operational_life: -2010
      potential: 5000.0
      status: future
      variable_cost: 0.0
  PWRWND:
    PWRWNDB01:
      capacity: 0.102
      capital_cost: 2278.07
      closure_year: 0
      name: BC_BMW00_GEN
      operational_life: -2009
      status: existing
      variable_cost: 0.0
    PWRWNDB02:
      capacity: 0.0992
      capital_cost: 2278.07
      closure_year: 0
      name: BC_CSS00_GEN
      operational_life: -2013
      status: existing
      variable_cost: 0.0
    PWRWNDB03:
      capacity: 0.144
      capital_cost: 2278.07
      closure_year: 0
      name: BC_DKW00_GEN
      operational_life: -2011
      status: existing
      variable_cost: 0.0
    PWRWNDB04:
      capacity: 0.1846
      capital_cost: 2278.07
      closure_year: 0
      name: BC_MKL00_GEN
      operational_life: -2015
      status: existing
      variable_cost: 0.0
    PWRWNDB05:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 0
      name: BC_MLW00_GEN
      operational_life: -2019
      status: existing
      variable_cost: 0.0
    PWRWNDB06:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 0
      name: BC_PSW00_GEN
      operational_life: -2010
      status: existing
      variable_cost: 0.0
    PWRWNDB07:
      capacity: 0.1422
      capital_cost: 2278.07
      closure_year: 0
      name: BC_QTY00_GEN
      operational_life: -2012
      status: existing
      variable_cost: 0.0
    PWRWNDB08:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 0
      name: BC_SHC00_GEN
      operational_life: -2010
      status: existing
      variable_cost: 0.0
    PWRWNDB09:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 0
      name: BC_SUK00_GEN
      operational_life: -2021
      status: existing
      variable_cost: 0.0
    PWRWNDB10:
      capacity: 0.015
      capital_cost: 2278.07
      closure_year: 0
      name: BC_ZBK00_GEN
      operational_life: -2021
      status: existing
      variable_cost: 0.0
    PWRWNDB11:
      capital_cost: 1735.2745158554371
      name: Cowichan Valley_1
      operational_life: -2009
      potential: 121.13643870188339
      status: future
      variable_cost: 0.0
    PWRWNDB12:
      capital_cost: 1735.2745158554371
      name: Mount Waddington_1
      operational_life: -2009
      potential: 584.8255365313626
      status: future
      variable_cost: 0.0
    PWRWNDB13:
      capital_cost: 1735.2745158554371
      name: Fraser Valley_1
      operational_life: -2009
      potential: 68.44150659859454
      status: future
      variable_cost: 0.0
    PWRWNDB14:
      capital_cost: 1735.2745158554371
      name: East Kootenay_1
      operational_life: -2009
      potential: 931.6267932886045
      status: future
      variable_cost: 0.0
    PWRWNDB15:
      capital_cost: 1735.2745158554371
      name: Sunshine Coast_1
      operational_life: -2009
      potential: 22.905823111389523
      status: future
      variable_cost: 0.0
    PWRWNDB16:
      capital_cost: 1735.2745158554371
      name: Peace River_1
      operational_life: -2009
      potential: 8271.063901768166
      status: future
      variable_cost: 0.0
clews_datapackage_template: models/BC_Nexus/csv_template