GADM:
  data: 'Global Administrative Regions (GADM)'
  supply_chain_mode: automated via python package "pygadm"
  source: https://gadm.org/download_country.html
  description: Regional boundaries of the Province.
  instruction: "Select 'Country', Check for the 'GeoJSON' type data and download 'level2'"
  remarks: "Geopackage, Shapefile data works similarly. This tool has been designed to fit with GeoJSON data."

CEEI: 
  data: Community Energy and Emissions Inventory
  supply_chain_mode: datafile downloading automated. 
  source:
    buildings: https://www2.gov.bc.ca/assets/gov/environment/climate-change/data/ceei/bc_utilities_energy_and_emissions_data_at_the_community_level.xlsx
    transportation: https://www2.gov.bc.ca/assets/gov/environment/climate-change/data/ceei/bc_on_road_transportation_data_at_the_community_level.xlsx
    waste: https://www2.gov.bc.ca/assets/gov/environment/climate-change/data/ceei/bc_municipal_solid_waste_data_at_the_community_level.xlsx
  description: Please check https://www2.gov.bc.ca/gov/content/environment/climate-change/data/ceei/methodology
  instruction: -
  remarks: -

NREL: 
  data :  # Annual technology Baseline (ATB) - 2024
  supply_chain_mode: datafile downloading automated. 
  source: # parquet file recommended for less memory usage
    # excel: https://data.openei.org/files/6006/2024%20v2%20Annual%20Technology%20Baseline%20Workbook%20Errata%207-19-2024.xlsx
    csv: https://oedi-data-lake.s3.amazonaws.com/ATB/electricity/csv/2024/ATBe.csv
    parquet: https://oedi-data-lake.s3.amazonaws.com/ATB/electricity/parquet/2024/ATBe.parquet
  description: https://atb.nrel.gov/electricity/2024/technologies
  instruction: -
  remarks: -

Statistics_Canada:
  data: Population projection 2021-2046.
  supply_chain_mode : Manual Download from the portal
  source: https://bcstats.shinyapps.io/popApp/
  description: Historical data up to 2023 and projection for 2024-2046.
  instruction: Manually download from the portal with mentioned steps.

    # Step 1: Select Data:
      #   Select the following options:
      #   Region Type: Regional District
      #   Regions: Select all regions under BC
      #   Select years: 2021 to 2046
      #   select gendres: Totals

    # Step 2: Choose Static
      # > Choose 'count'

    # Step 3: Select age format
      # > Choose "Totals"

    # Step 3: Customize Layout
      # > Choose "None"
    
    # > generate output
    # > Download csv
    # in the downloaded CSV file : Delete all the rows on top until you get the column names.
  remarks: The data source can be replaced but may need to format the data to fit with the scripts.
  mapping:
    different_name_mapping:
      Columbia Shuswap: Columbia-Shuswap
      Comox-Strathcona: Strathcona
      Greater Vancouver: Metro Vancouver
      Powell River: qathet
      Skeena-Queen Charlotte: North Coast
      Stikine: Stikine (Census Division)
      Northern Rockies: Northern Rockies (Census Division)



