
Regions:
  region_1:
    code: 'BC'
    name: 'British Columbia' # Case Sensitive, and needs to be exact same as supported by GADM
    area: 944735 #sqkm
    boundary:
      GADM_directory : data/GADM
      GADM_file: data/GADM/BC/BC_gadm_regions.geojson
    conservation_lands_provincial_id: 2 # CPACD data, col : LOC, for more info check https://data-donnees.az.ec.gc.ca/api/file?path=/species%2Fprotectrestore%2Fcanadian-protected-conserved-areas-database%2FProtectedConservedAreaUserManual.pdf
    conservation_lands_datafile: data/Gov/Conservation_Lands/BC/CPCAD_BC_union.pkl
    grid_nodes_data: data/Processed_data/Transmission/BC/Transmission.pkl

CODERS:
  data: Canadian Open Data on Energy Resources and System (CODERS) from SESIT Group, UViC,BC, Canada.
  source:
    url_1: https://sesit.dev/
    url_2: http://206.12.95.102/
    api_key:
      contact_for_request: modellingteam.sesit@uvic.ca
      Elias: w0OksqQKMFMtKPbO
    api_documentation: https://sesit.dev/api/docs
  instruction: contact - modellingteam.sesit@uvic.ca for access request approval.
  remarks: May have to sign an End User License Aggrement (EULA).
  data_save_to: datapackage/data_supply_chain/CODERS

GADM:
  data: 'Global Administrative Regions (GADM)'
  source: https://gadm.org/download_country.html
  instruction: "Select 'Country', Check for the 'GeoJSON' type data and download 'level2'"
  remarks: "Geopackage, Shapefile data works similarly. This tool has been designed to fit with GeoJSON data."