# Title: User Configuration for BCNexus model
# Developer: Md Eliasinul Islam
# Affiliation: Sustainable Energy Engineering, Simon Fraser University, BC, Canada
# ------------------
# version: 2.0
# Release_Year: 2025
# ------------------
info_SCENARIOS:
  # aligned with folder name
  Model_Kotzur_Base_CNZ: "Baseline scenario with Canada Energy Futures 2023 report's Canada Net Zero Demand. Call for Power 2024 sites fitted as committed plants. Potential resource options for Solar (5GW) and Wind (10GW) modeled. Hourly profiles absorbed from 2021 historical data. Allowed CCS ( <= 0.2 GW) and HDG (<=0.2 GW) from 2026"
  Model_Kotzur_CNZ_LIMITED_CO2: "Baseline scenario with CO2 annual limit up to 50 MTeCO2."
  Model_Kotzur_CNZ_LIMITED_CO2_PLTY: "Baseline scenario with emission penalty up to $170/MTeCo2. "
  Model_Kotzur_HYDROGEN: "Hydrogen intense scenario with sectoral hydrogen demand assumptions and no emission limit, no limit on CCS, HDG techs."
  Model_Kotzur_NUC_standard_2028: "Standard Nuclear scenario with Investment allowed from Y2028. All other assumptions are same as Base_CNZ scenario."
  Model_Kotzur_NUC_standard_2028_2xCost: "Expensive Nuclear scenario with Investment allowed from Y2028. All other assumptions are same as Base_CNZ scenario. Cost of Nuclear is 2x the standard cost."
  Model_Kotzur_NUC_standard_2030: "Standard Nuclear scenario with Investment allowed from Y2030. All other assumptions are same as Base_CNZ scenario."
  Model_Kotzur_NUC_standard_2030_2xCost: "Expensive Nuclear scenario with Investment allowed from Y2030. All other assumptions are same as Base_CNZ scenario. Cost of Nuclear is 2x the standard cost."
  Model_Kotzur_NUC_standard_2035: "Standard Nuclear scenario with Investment allowed from Y2035. All other assumptions are same as Base_CNZ scenario."
  Model_Kotzur_NUC_standard_2035_2xCost: "Expensive Nuclear scenario with Investment allowed from Y2035. All other assumptions are same as Base_CNZ scenario. Cost of Nuclear is 2x the standard cost."
  Model_Kotzur_NUC_standard_2035_4xCost: "Expensive Nuclear scenario with Investment allowed from Y2035. All other assumptions are same as Base_CNZ scenario. Cost of Nuclear is 4x the standard cost."
  Model_Kotzur_Base_CNZ_2: Description

SCENARIOS:
  # scneario_name: ####### CAN'T DELETE, CAN BE EMPTY
  # scenario_axes: ####### CAN'T DELETE, CAN BE EMPTY
  # TECHID:   ####### CAN BE EMPTY/deleted
  # capital_cost: float or vector
  # operational_life: int
  # input_fuel: supported FUELS
  # efficiency: float
  # total_annual_min_capacity: float
  # total_annual_max_capacity: float 
  # total_annual_max_capacity_investment : float
  # Base_CM:
  #   Demand: {}
  #   EMISSION: {}
  #   TECHS: 
  #     CCS01:
  #         capital_cost: 9999 # we can also prove a vector e.g. [xxx xxx ]
  #         total_annual_max_capacity: 0.2 #GW
  #         operational_life: 25
  #         total_annual_max_capacity_investment: '[0,0,0,0,0,1]'
  #     HDG01:
  #         total_annual_max_capacity: 0.2 #GW
  #         total_annual_max_capacity_investment: '[0,0,0,0,0,1]'

  #scenario
  Base_CNZ:
    Demand: {}
    EMISSION: {}
    TECHS:
      CCS01:
        capital_cost: 9999 # we can also prove a vector e.g. [xxx xxx ]
        total_annual_max_capacity: 0.2 #GW
        operational_life: 25
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 1 ]
      HDG01:
        operational_life: 25
        total_annual_max_capacity: 0.2 #GW
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 1 ]
  Base_CNZ_noCCS:
    Demand: {}
    EMISSION: {}
    TECHS:
      CCS01:
        capital_cost: 9999 # we can also prove a vector e.g. [xxx xxx ]
        total_annual_max_capacity: 0 #GW
        operational_life: 25
        total_annual_max_capacity_investment: [ 0 ]
      HDG01:
        total_annual_max_capacity: 0.2 #GW
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 1 ]
    # remarks:
    #   "Baseline"
    #scenario
  CNZ_LIMITED_CO2:
    Demand: {}
    EMISSION:
      CO2:
        annual_emission_limit: 70
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

  #scenario
  CNZ_LIMITED_CO2_PTY:
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

  #scenario
  IMP_USA_100:
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      PWRIMPB01:
        # Import from USA
        capacit: 0.571 #GW from [4,500 GWh /(8,760 × 0.9)]
        # capital_cost: 7863 # $/kW
        availability_factor: 0.9
        efficiency: 1
        operational_life: 50 #years
        total_annual_min_capacity: 0.571 # float
        total_annual_max_capacity: 0.571 # float

      PWRURNB01:
        # Nuclear
        capital_cost: 7863 # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2028          
  #scenario
  NUC_standard_2028:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

      PWRURNB01:
        # Nuclear
        capital_cost: 7863 # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2028

  NUC_standard_2028_2xCost:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

      PWRURNB01:
        # Nuclear
        capital_cost: 15726 # (7863*2)  # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2028

  NUC_standard_2030:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

      PWRURNB01:
        # Nuclear
        capital_cost: 7863 # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2030

  NUC_standard_2030_2xCost:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

      PWRURNB01:
        # Nuclear
        capital_cost: 15726 # (7863*2)  # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2030

  NUC_standard_2035:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

      PWRURNB01:
        # Nuclear
        capital_cost: 7863 # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2035

  NUC_standard_2035_2xCost:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20

      PWRURNB01:
        # Nuclear
        capital_cost: 15726 # (7863*2)  # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        total_annual_min_capacity: # GW
        total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2035
  NUC_standard_2035_4xCost:
    # NUC + CNZ_LIMITED_CO2_PTY
    Demand: {}
    EMISSION:
      CO2:
        # annual_emission_limit: [70,70,70,60,60,50]
        emission_penalty: [ 45, 45, 50, 65, 80, 95, 110, 125, 140, 155, 170 ]
    TECHS:
      CCS01:
        capital_cost: 9999
        operational_life: 20
      PWRURNB01:
        # Nuclear
        capital_cost: 31452 # (7863*2)  # $/kW
        # NREL ATB 2024, Moderate Scenario, Market price of 2035 , CAPEX 7863 USD/kW, FOM  136 USD/kW, VOM 2.6 USD/kWh
        efficiency: 0.3333
        input_fuel: PWRURN
        operational_life: 35 #years
        # total_annual_min_capacity: # float
        # total_annual_max_capacity: # float 
        total_annual_max_capacity_investment: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] # from 2035
  #scenario

  # HYDROGEN:
  #   Demand:
  #     TRAHDG:
  #       accumulated_annual_demand: [0, 0, 0, 0, 8.959, 12.92544, 16.78746, 20.59696, 24.78204, 28.8464, 33.0876, 37.3422, 41.67892, 46.19744, 50.7708, 55.3486, 59.96458, 64.57248, 69.22646, 73.9898, 78.8523, 83.83752, 88.98146, 94.3254, 99.9061, 105.73824, 111.8196, 118.14444, 124.72084, 131.544]
  #     TRADSL:
  #       accumulated_annual_demand: [97.11, 96.19, 97.68, 94.33, 89.015, 85.6544, 81.55812, 77.73012, 76.32148, 73.7688, 71.91856, 69.91268, 67.9959, 66.31136, 64.5758, 62.73588, 60.8825, 58.9632, 57.06738, 55.2482, 53.46718, 51.73056, 50.0539, 48.44924, 46.9098, 45.41816, 43.94846, 42.47748, 40.9973, 39.492]
  #     TRAJFL:
  #       accumulated_annual_demand: [39.94, 72.29, 80.01, 82.62, 81.206, 80.94016, 80.24442, 79.23292, 78.47648, 77.6748, 76.79384, 75.79512, 74.74518, 73.7712, 72.6934, 71.46552, 70.12292, 68.64432, 67.07616, 65.472, 63.83052, 62.16192, 60.47464, 58.77536, 57.0741, 55.3636, 53.63194, 51.86808, 50.06186, 48.204]
  #     INDHDG:
  #       accumulated_annual_demand: [0, 0, 0, 0, 12.6015, 19.85976, 25.12244, 29.99528, 38.1984, 47.5776, 53.90294, 59.80872, 67.32992, 75.12912, 82.2798, 89.09212, 95.4874, 102.01968, 108.8857, 116.0596, 123.49842, 131.0372, 138.73722, 146.78352, 155.1634, 163.84512, 172.8024, 182.0344, 191.56076, 201.36]
  #     INDNGS:
  #       accumulated_annual_demand: [218.37, 229.17, 236.88, 230.18, 239.4285, 255.97024, 242.13756, 228.58472, 238.6016, 249.7824, 242.26706, 233.37128, 230.59008, 227.81088, 222.4602, 216.01788, 208.6126, 201.61032, 195.2643, 189.3604, 183.71158, 178.0128, 172.33278, 166.85648, 161.4966, 156.16488, 150.7976, 145.3656, 139.85924, 134.24]
  #   EMISSION: 
  #     CO2:
  #       annual_emission_limit: 9999
  #       emission_penalty: 0
  #   TECHS: 
  #     CCS01:
  #       capital_cost: 9999
  #       operational_life: 20


  # # Baseline Calibration with scenario config
  #     calibration:
  #       Demand: {}
  #       EMISSION: {}
  #       TECHS: 
  #         PWRHYDB01:
  #             total_annual_max_capacity_investment: 0
  #         PWRHYDB02:
  #             total_annual_max_capacity_investment: 0
  #         PWRNGSB01:
  #             total_annual_max_capacity_investment: 0
  #         PWRNGSB02:
  #             total_annual_max_capacity_investment: 0
  #         PWRBIOB01:
  #             total_annual_max_capacity_investment: 0
  #         PWRBIOB02:
  #             total_annual_max_capacity_investment: 0
  #         PWRGEOB01:
  #             total_annual_max_capacity_investment: 0
  #         PWRSOLB01:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB01:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB02:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB03:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB04:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB05:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB06:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB07:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB08:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB09:
  #             total_annual_max_capacity_investment: 0
  #         PWRWNDB10:
  #             total_annual_max_capacity_investment: 0
  #         PWRSOLB04:
  #           total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
  #         PWRSOLB05:
  #           total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
  #         PWRSOLB06:
  #           total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
  #         PWRSOLB07:
  #           total_annual_max_capacity: '[0,0,0,0,0,0,0,0,0,0,0]'
  #         CCS01:
  #             capital_cost: 9999 # we can also prove a vector e.g. [xxx xxx ]
  #             total_annual_max_capacity: 0.2 #GW
  #             operational_life: 25
  #             total_annual_max_capacity_investment: '[0,0,0,0,0]'
  #         HDG01:
  #             total_annual_max_capacity_investment: '[0,0,0,0,0]'
